### ISSUE TITLE
Time Zone Offset issue with Cabu Page

### ISSUE THREAD

**Issue by aprsandrew** [aprsworld/craneWeb#8]
After midnight UTC, the cabu page no longer works properly.  Tablet battery and min/max values no longer shown.  Believe it is a time-zone offset issue.  Setting the crane logger's time-zone offset to UTC in deviceInfo table makes it start working again.  See example screenshots below.

![screenshot from 2016-05-10 20 49 39](https://cloud.githubusercontent.com/assets/7646844/15167763/31c200d0-16f1-11e6-9277-833063e5457b.png)

![screenshot from 2016-05-10 20 50 50](https://cloud.githubusercontent.com/assets/7646844/15167765/38e051a0-16f1-11e6-85c8-b370bbfaa9f9.png)

**Comment by Cdetviler** [comment]
I believe I have fixed this. all queries for R72 ( tied to a cabu in central timezone) were looking for packets starting at 5:00am through 5:00am the next day. This is problematic for any time between 12:00am and 4:59am. I will try to test this at midnight to see if it is working.

**Comment by aprsandrew** [comment]
This is still an issue.  Even with the version in crane2/craneWeb

Just past midnight UTC, and issue is showing up for any sites with a negative timezone offset.  Tried setting a unit to UTC-6, -5, -4, -3, etc...  Only way to get it to display min/max values is to set it to offset of 0.  And then, of course it is only showing the min/max since midnight UTC (ie, from the past 13 minutes as it is 00:13:00 UTC or so right now).

**Comment by Cdetviler** [comment]
I will have to do some testing on this either tonight or tomorrow night to make sure that this is fixed.

**Comment by Cdetviler** [comment]
This has now been tested by Andrew and I. It is working correctly.
